[book]
authors = ["Francisco Perez-Sorrosal"]
language = "en"
multilingual = false
src = "src"
title = "AI Resources"
bibliography = "biblio.bib"
[output.html]
theme = "src/theme"
mathjax-support = true
