[book]
authors = ["Francisco Perez-Sorrosal"]
language = "en"
multilingual = false
src = "src"
title = "AI Resources"
[output.html]
theme = "src/theme"
mathjax-support = true

[preprocessor.bib]
bibliography = "my_zotero.bib"
zotero-uid = "6957968"
render-bib = 'all'